### ISSUE TITLE
GPS log download creates invalid GPX file

### ISSUE THREAD

**Issue by johannessen** [mbof/hxsync#22]
Downloading a GPS log from my HX870 resulted in a GPX file looking similar to the following (whitespace added here for clarity):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Nghx" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns="http://www.topografix.com/GPX/1/1"
 xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
<trk>
  <trkseg>
    <trkpt lat="59.59691390991211" lon="4.788832187652588">
      <ele>0</ele>
      <time>1592832147</time>
      <fix>2</fix>
      <spd>1</spd>
      <trk>273</trk>
    </trkpt>
  </trkseg>
</trk>
</gpx>
```

This XML doesn’t pass schema validation, which causes interoperability problems with some software such as QGIS.

- `<time>` contains values not allowed by GPX schema
- `<fix>` contains values not allowed by GPX schema
- `<spd>` element is not allowed by GPX schema
- `<trk>` inside `<trkpt>` is not allowed by GPX schema

See <https://www.topografix.com/gpx.asp> for further information. Perhaps the speed etc. could be added as a GPX comment in a `<cmt>` element.

**Comment by mbof** [comment]
Thanks for reporting! I think this is fixed.

* Formatted timestamp using `xs:datetime` format
* Reordered elements to match syntax
* Changed the fix type to match accepted types, and removed it when the interpretation isn't clear
* Stashed the track and speed information in the `<cmt>` element as suggested, encoded in JSON in case machine reading is desirable
* Verified that it validates with `xmllint`

Please give it a try at https://mbof.github.io/hx/ if you get a chance.

**Comment by johannessen** [comment]
Confirm fixed.

That was quick work! 😀
