### ISSUE TITLE
Add indication of process duration

### ISSUE THREAD

**Issue by johannessen** [mbof/hxsync#25]
During testing, I experienced the connection to “hang” while loading the GPS log. I broke the connection after waiting over five minutes, as it clearly wasn’t going anywhere.

Ideally, there would be a progress bar, similar to SH’s YCE applications.

At minimum, I propose to add a legend informing the user of the expected duration. For example: “Downloading GPS log. This should take about 60 seconds.”

(It takes ~ 55 seconds for my log with around 800 points. Might take longer if you have more points, I’m not sure. What’s the maximum number of points you can have in the log? I forgot…)

**Comment by mbof** [comment]
Added a percentage indicator
<img width="914" alt="image" src="https://github.com/mbof/hxsync/assets/1308709/d413b655-4961-4c29-a253-30c3a320b536">
