### ISSUE TITLE
Waypoint names are not FF-padded

### ISSUE THREAD

**Issue by johannessen** [mbof/hxsync#26]
Waypoints created on the HX870 itself, with YCE15, or with hxtool have names looking like this:
```
00004310: 3030 3457 5054 ffff ffff ffff ffff ff04   004WPT..........
```
Waypoints names written to the device with this app look like this:
```
00004310: 3030 3457 5054 2020 2020 2020 2020 0004   004WPT        ..
```
Note the difference in padding: SH uses their standard practice of marking all unused bytes with `FF`. This app currently fills up the name with spaces, then adds a single `00` byte as padding at the end. While the HX870 doesn’t seem to care, this creates interoperability issues when switching between this app and other software to handle waypoints.

**Comment by mbof** [comment]
I believe the padding with spaces and a null byte was what I had observed on-device editor to do on my HX890, so I was replicating that. But if the device handles 0xFF bytes as padding fine, I'll switch to that.
