### ISSUE TITLE
Waypoints lose their DSC address on round-trip

### ISSUE THREAD

**Issue by johannessen** [mbof/hxsync#27]
Waypoints created from a received DSC position report include the originating DSC address. It seems that this information is lost when writing waypoints back to the device.

For example, consider the following HX870 memory, with a waypoint hypothetically received from MMSI 987 654 321:
```
00004300: 9876 5432 1044 2400 0053 0040 0240 0057  .vT2.D$..S.@.@.W
```

To reproduce, add a new waypoint with this app, but don’t change the existing one. The memory of the existing waypoint then changes to this:
```
00004300: ffff ffff f044 2400 0053 0040 0240 0057  .....D$..S.@.@.W
```

Admittedly, I’m not sure if the DSC address is actually used for anything in the device, but I still think that using this app shouldn’t destroy existing data unless asked to do so.

**Comment by mbof** [comment]
I think this is fixed and pushed to mbof.github.io/hx/, but I don't have a good way to test. @johannessen if you are able to verify the fix, it would be much appreciated!

**Comment by johannessen** [comment]
Sure! Will look into it when I can. Hopefully this weekend; I’ll be away from the radio for a while after that.

**Comment by johannessen** [comment]
Confirm fixed. Thanks!
