### ISSUE TITLE
Waypoint names shouldn't include characters incompatible with the device

### ISSUE THREAD

**Issue by mbof** [mbof/hxsync#29]
Repro steps:
1. Using HxSync, create waypoints that contain parentheses in the name
2. View the waypoints on device

Observed:
* The parentheses show up as spaces as they are not supported.

Expected:
* Users get an error in the waypoint editing dialog showing what the unsupported characters are (e.g. "Waypoint name cannot contain ()"), in the same way that they get warned about waypoint name length.

From what I can tell, aside from 0-9, A-Z, and a-z, the only supported characters in the font are `!"#%&'*+,-.:<>?[]_`.
Of the printable ASCII characters, that leaves out ``$();=@\^`{|}~``

**Comment by johannessen** [comment]
Looks like the HX890 supports more chars than the HX870.
