### ISSUE TITLE
Support editing routes

### ISSUE THREAD

**Issue by mbof** [mbof/hxsync#5]
After waypoints are supported, routes should be supported.

**Comment by mbof** [comment]
The plan is to handle waypoint editing and route editing in a joint "navigation planning" mode, which will replace the current waypoint-only editing mode. When entering the navigation planning mode, both waypoint and route info will be loaded; and when leaving the mode, both waypoint and route info will be written.

The intended plan is roughly as follows:
1. Build serializers and parsers to handle conversion of route information to/from the binary storage format.
2. Add route editing capabilities to the DraftWaypoints component, which currently manages model state for waypoint editing. Route editing means adding, deleting, and renaming routes; inserting, changing, swapping, or deleting waypoints within them.
3. Add reading and writing of routes to the waypoint read/write routines
4. Add UI in the waypoint sheet to let users edit routes in addition to waypoints

**Comment by johannessen** [comment]
FWIW, route navigation [is not something many people do with the radio](https://groups.io/g/hx870-hx890/message/580).

**Comment by mbof** [comment]
Thanks for the previous research! I mostly go out on boats that either don't have other nav equipment or that have nav equipment I'm not familiar with, so I might be an outlier in that I rely on my portable radio as primary navigation device. But even then, I don't use routes often. Good to know that this may not be an overall high priority.

**Comment by mbof** [comment]
Supported in YAML now
